### ISSUE TITLE
It loop loading animation

### ISSUE THREAD

**Issue by Thanawatttt** [Zeptosec/ThermostoreFront#2]
**Desktop (please complete the following information):**
 - OS: android
 - Browser chrome

**Additional context**
Selfhost

**Comment by Zeptosec** [comment]
## Insights
This project requires a lot of setup on supabase side. The problem is that there is no easy way to dump all the functions from supabase and provide a quick and easy one button setup.

I was creating this project for the purposes of learning so this project is somewhat broken.

Another thing soon (somewhere in 2023 December) this project won't work at all because of the discords new policy to expire links after 24h from when they were created. The project will require some changes to make it work again.

## Addressing your issue
As for your problem I would guess that you haven't setup supabase properly, because I haven't updated the readme file in a while.
The function that fetches files and directories from database is here:
https://github.com/Zeptosec/Thermastore/blob/e545a8ebfe1eaf32b3ea7c5ff6bbb90f3efc6c14/src/utils/FileFunctions.ts#L519
And it is a supabase function so you'll need to create it manually in `Database > functions` or by going to `SQL editor`.
https://github.com/Zeptosec/Thermastore/blob/64223eeb6e9792ece684814ab58c379d44ff3d85/supabase.ddl#L31-L131

**Comment by Thanawatttt** [comment]
so can you make same as this project but use telegram bot?

**Comment by Zeptosec** [comment]
I've tinkered a little bit with telegram bot api and TDLib, but telegram handles their attachment links differently. I need to do some more testing.

There is some kind of cloud storage made with telegram api called `UnLim`. It's not open source, but maybe it will fit your needs.
