### ISSUE TITLE
add this feature

### ISSUE THREAD

**Issue by bianvigano** [Zeptosec/ThermostoreFront#6]
- You can delete it from the database or from the discord link or file from discord
- can see how much we or the user uploaded (such as how many percent of what has been uploaded or the normal of the amount that has been uploaded)

**Comment by Zeptosec** [comment]
> * You can delete it from the database or from the discord link or file from discord

I don't really understand what do you mean by that. If you delete any part of the file from the discord you won't be able to download the file because pieces will be missing and so the file will be corrupted although if it's a video or audio file it could still be playable to some extent. And implementing file deletion would require to use a **discord bot** which i won't implement into this system because of how insecure that would be. Webhooks are safe they can only send messages to a specific channel they can't read or delete them. If you'd like to delete files from discord you can link your webhook to a specific channel then when you want to make those files inaccessible you can just delete the whole channel. Or you can create a simple discord bot script which would delete specified files from your discord channel.
> * can see how much we or the user uploaded (such as how many percent of what has been uploaded or the normal of the amount that has been uploaded)

This one I also can't fully comprehend. I'm assuming you'd like to see files by categories (audio, video, text). This one would actually be nice and maybe I'll implement it in the near future.
